name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Install Azure CLI manually
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Verify Azure CLI installation
      run: |
        az --version

    - name: Log in to Azure
      run: |
        az login --service-principal --username ${{ secrets.AZURE_APP_ID }} --password ${{ secrets.AZURE_APP_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    - name: Docker Login to ACR
      run: az acr login --name dtsazurecr

    - name: Build and Push Frontend Image
      run: |
        docker build -t dtsazurecr.azurecr.io/frontend:latest ./frontend/task-managment
        docker push dtsazurecr.azurecr.io/frontend:latest

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'   # or 'zulu' or others
        java-version: '17'  
    
    - name: Build backend JAR
      run: |
        cd backend
        ./mvnw clean package -DskipTests
    
    - name: Build and Push Backend Image
      run: |
        docker build -t dtsazurecr.azurecr.io/backend:latest ./jds
        docker push dtsazurecr.azurecr.io/backend:latest

