name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build and push frontend Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:1.0

    - name: Build and push backend Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/backend
        
    - name: Install Azure CLI manually
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Verify Azure CLI installation
      run: |
        az --version

    - name: Log in to Azure
      run: |
        az login --service-principal --username ${{ secrets.AZURE_APP_ID }} --password ${{ secrets.AZURE_APP_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
    - name: Deploy Docker containers to Azure
      run: |
        # for azure

    - name: Deploy with Kubernetes (if applicable)
      run: |
        # for kubectl
